{{ if and .Values.additionalConf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-conf
  labels:
    app: {{ include "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "fullname" . }}
    helm.sh/chart: {{ include "chart" . }}
data:
{{- with .Values.additionalConf.data }}
{{ toYaml . | indent 2 }}
{{- end }}
{{ end }}
