fullnameOverride: demo-was

replicaCount: 1

profile: default

namespace: default

image:
  repository: devosquickstarter/eks-demo-was
  tag: latest
  pullPolicy: Always

dockerRegistrySecret: regcred

labels: {}
annotations: {}

pod:
  labels: {}
  annotations: {}

serviceaccount: eks-user

command: {}
# - "/bin/sh"
# - "-c"
args: {}
# - ". /vault/secrets/config && exec java $JAVA_OPTS -jar ROOT.jar"

pdb: {}

service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  annotations: {}
  labels: {}

ingress:
  enabled: true
  subdomain: demo-was
  basedomain: 127.0.0.1.nip.io
  hosts: {}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels: {}

autoscaling:
  enabled: true
  min: 1
  max: 5
  cpu: 80
  mem: 80
  custom: {}

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1024Mi

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

nodeSelector: {}

tolerations: []

affinity: {}

env: {}

language: java

java:
  options: "-XX:InitialRAMPercentage=40.0 -XX:MaxRAMPercentage=80.0"

pinpoint:
  enabled: false
  sampling: 1
  collectorIp: pinpoint-collector.monitor.svc.cluster.local

configmap:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

additionalConf:
 enabled: false
